import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/SupabaseServerClient";

export async function GET(req: NextRequest) {
  const supabase = await createClient();
  // Auth check
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ invoices: [] }, { status: 401 });
  }
  // Org check
  const orgId = req.cookies.get("current_org_id")?.value;
  if (!orgId) {
    return NextResponse.json({ invoices: [] }, { status: 400 });
  }
  const searchParams = req.nextUrl.searchParams;
  const id = searchParams.get("id");

  let query = supabase
    .from("invoices")
    .select(`*, users:user_id(id, first_name, last_name, email, user_organizations!inner(organization_id))`)
    .eq("organization_id", orgId);

  if (id) {
    query = query.eq("id", id);
  }
  // Only include users who are members of the org
  query = query.eq("users.user_organizations.organization_id", orgId);

  const { data, error } = await query;
  if (error) {
    return NextResponse.json({ invoices: [] }, { status: 500 });
  }
  return NextResponse.json({ invoices: data ?? [] });
}

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const body = await req.json();
  const { organization_id, user_id, booking_id, status = 'draft' } = body;
  if (!organization_id || !user_id) {
    return NextResponse.json({ error: 'Missing organization_id or user_id' }, { status: 400 });
  }
          // Invoice number will be automatically generated by database trigger
    const invoice_number = null;
    const now = new Date();
    const issue_date = now.toISOString().slice(0, 10);
    const due_date = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10); // +14 days
  const { data, error } = await supabase
    .from('invoices')
    .insert([
      {
        organization_id,
        user_id,
        booking_id: booking_id || null,
        invoice_number,
        issue_date,
        due_date,
        status,
        subtotal: 0,
        tax_amount: 0,
        tax_rate: 0.15,
        total_amount: 0,
      },
    ])
    .select('id')
    .single();
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  return NextResponse.json({ id: data.id });
}

export async function PATCH(req: NextRequest) {
  const supabase = await createClient();
  const body = await req.json();
  const { id, ...updateData } = body;
  
  if (!id) {
    return NextResponse.json({ error: 'Missing invoice id' }, { status: 400 });
  }

  // Auth check
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Org check
  const orgId = req.cookies.get("current_org_id")?.value;
  if (!orgId) {
    return NextResponse.json({ error: 'Missing organization' }, { status: 400 });
  }

  // Verify the invoice belongs to the organization
  const { data: existingInvoice } = await supabase
    .from("invoices")
    .select("id")
    .eq("id", id)
    .eq("organization_id", orgId)
    .single();

  if (!existingInvoice) {
    return NextResponse.json({ error: 'Invoice not found' }, { status: 404 });
  }

  // Update the invoice
  const { data, error } = await supabase
    .from("invoices")
    .update(updateData)
    .eq("id", id)
    .eq("organization_id", orgId)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ invoice: data });
}

export async function DELETE() {
  // TODO: Implement DELETE invoice
  return NextResponse.json({ message: "DELETE invoice" });
} 